WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 900
PADX = 20
PADY = 20
BACKGROUND_COLOR = '#1A1A40'
FPS = 60
FONT_SIZE = 30
TEXT_COLOR = '#AEFEFF'

# game values
SHIP_VELOCITY = 10
SHIP_LIVES = 5
SHIP_BULLET_CAPACITY = 5
BULLET_VELOCITY = 10
ALIEN_ROWS = 5
ALIEN_COLS = 10
ALIEN_VELOCITY = 1
ALIEN_ADVANCE_INCREMENT = 70
